// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(
  "ch.qos.logback" % "logback-classic" % "1.2.3",
  "ch.qos.logback" % "logback-core" % "1.2.3",
  "com.chuusai" % "shapeless_2.12" % "2.3.3",
  "com.github.pureconfig" % "pureconfig-macros_2.12" % "0.9.1",
  "com.github.pureconfig" % "pureconfig_2.12" % "0.9.1",
  "com.github.scopt" % "scopt_2.12" % "3.7.0",
  "com.typesafe" % "config" % "1.3.3",
  "com.typesafe.scala-logging" % "scala-logging_2.12" % "3.9.0",
  "io.monix" % "monix-eval_2.12" % "3.0.0-RC1",
  "io.monix" % "monix-execution_2.12" % "3.0.0-RC1",
  "org.reactivestreams" % "reactive-streams" % "1.0.2",
  "org.scoverage" % "scalac-scoverage-runtime_2.12" % "1.3.1",
  "org.slf4j" % "slf4j-api" % "1.7.25",
  "org.typelevel" % "cats-core_2.12" % "1.1.0",
  "org.typelevel" % "cats-effect_2.12" % "0.10",
  "org.typelevel" % "cats-kernel_2.12" % "1.1.0",
  "org.typelevel" % "cats-macros_2.12" % "1.1.0",
  "org.typelevel" % "machinist_2.12" % "0.6.2",
  "org.typelevel" % "macro-compat_2.12" % "1.1.1"
)
// LIBRARY_DEPENDENCIES_HASH b87dd926583675c99c070f068c6ec36b25833d82
