// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(
  "org.scoverage" % "scalac-scoverage-runtime_2.12" % "1.3.1"
)
// LIBRARY_DEPENDENCIES_HASH 858dbdeeb1557e498f00e97d35046644f5b00a3b
