// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(

)
// LIBRARY_DEPENDENCIES_HASH 0c1ecb84eefded81e31012edb83a33973e7edae4
