// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(

)
// LIBRARY_DEPENDENCIES_HASH a7752052be10e08cb939d3fea8c8665360d973d4
