// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(
  "com.chuusai" % "shapeless_2.12" % "2.3.3",
  "org.scala-lang.modules" % "scala-collection-compat_2.12" % "0.1.1",
  "org.typelevel" % "alleycats-core_2.12" % "1.3.1",
  "org.typelevel" % "cats-core_2.12" % "1.3.1",
  "org.typelevel" % "cats-kernel_2.12" % "1.3.1",
  "org.typelevel" % "cats-macros_2.12" % "1.3.1",
  "org.typelevel" % "export-hook_2.12" % "1.2.0",
  "org.typelevel" % "kittens_2.12" % "1.1.1",
  "org.typelevel" % "machinist_2.12" % "0.6.5",
  "org.typelevel" % "macro-compat_2.12" % "1.1.1"
)
// LIBRARY_DEPENDENCIES_HASH f39d43635b859c6fab7bb175910e0856a4e372dc
