// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(
  "com.chuusai" % "shapeless_2.12" % "2.3.3",
  "com.chuusai" % "shapeless_sjs0.6_2.12" % "2.3.3",
  "org.scala-js" % "scalajs-library_2.12" % "0.6.28",
  "org.typelevel" % "alleycats-core_2.12" % "1.6.0",
  "org.typelevel" % "alleycats-core_sjs0.6_2.12" % "1.6.0",
  "org.typelevel" % "cats-core_2.12" % "1.6.0",
  "org.typelevel" % "cats-core_sjs0.6_2.12" % "1.6.0",
  "org.typelevel" % "cats-kernel_2.12" % "1.6.0",
  "org.typelevel" % "cats-kernel_sjs0.6_2.12" % "1.6.0",
  "org.typelevel" % "cats-macros_2.12" % "1.6.0",
  "org.typelevel" % "cats-macros_sjs0.6_2.12" % "1.6.0",
  "org.typelevel" % "export-hook_2.12" % "1.2.0",
  "org.typelevel" % "kittens_sjs0.6_2.12" % "1.2.1",
  "org.typelevel" % "machinist_2.12" % "0.6.6",
  "org.typelevel" % "machinist_sjs0.6_2.12" % "0.6.6",
  "org.typelevel" % "macro-compat_2.12" % "1.1.1"
)
// LIBRARY_DEPENDENCIES_HASH 980a65e78ef2cedcbbc351bbf56e6fa6a86829f9
